<?php

namespace Biblioteca\TegBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * tegRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tegRepository extends EntityRepository
{
	/**
	 * Our new getAllPosts() method
	 *
	 * 1. Create & pass query to paginate method
	 * 2. Paginate will return a `\Doctrine\ORM\Tools\Pagination\Paginator` object
	 * 3. Return that object to the controller
	 *
	 * @param booleam $published true si solo se muestran los publicos, false todos los teg existentes
	 * 
	 * @return \Doctrine\ORM\Tools\Pagination\Paginator
	 */
	public function search($data = null, $published = true)
	{
        printf("<pre>");print_r($data); printf("</pre>");
	    // Create our query
	    $query = $this->createQueryBuilder('t');
    	if (isset($data['q'])) {
            $exprQ = $query->expr()->orX(
                $query->expr()->like('t.cota', "'%".$data['q']."%'"),
                $query->expr()->like('t.titulo', "'%".$data['q']."%'"),
                $query->expr()->like('t.escuela', "'%".$data['q']."%'"),
                $query->expr()->like('t.resumen', "'%".$data['q']."%'")//,
                //$query->expr()->like('t.palabrasClave', "'%".$data['q']."%'")//,
                //$query->expr()->like('t.autores', "'%".$data['q']."%'"),
                //$query->expr()->like('t.tutores', "'%".$data['q']."%'")
            );
        }
        else
        {
            $exprQ = $query->expr()->isNotNull('t.titulo');
        }

        //Si se filtra por Escuela se 
        if (isset($data['escuela'])){
            $exprEscuela = $query->expr()->eq('t.escuela', "'".$data['escuela']."'");}
        else{$exprEscuela = $query->expr()->isNotNull('t.escuela');}

        
        //Si rangos de fechas es ignorado
        if (!isset($data['desde']) && !isset($data['hasta'])){
            $exprInteval= $query->expr()->isNotNull('t.publicacion');}
        else{
            //Si ingreso rango inferior
            if (isset($data['desde'])) {
                $desde = "'".$data['desde']."-1-1'";
            }else{$desde = 't.publicacion';}
            //Si ingreso rango superior
            if (isset($data['hasta'])) {
                $hasta = "'".$data['hasta']."-12-31'";
            }else{$hasta = 't.publicacion';}
            $exprInteval = $query->expr()->between('t.publicacion', $desde, $hasta);
        }
        //Se unen en AND las codiciones
        $condiciones = $query->expr()->andX(
                    $query->expr()->eq('t.published', "'".$published."'"),
                    $exprEscuela,
                    $exprInteval,
                    $exprQ
        );
        printf("<pre>");/*print_r($condiciones);*/ printf("</pre>");
        
        $query->where($query->expr()->andX($condiciones))
        ->orderBy('t.publicacion', 'DESC')->getQuery();
$result = $query->getResult();
printf("<pre>");

print_r($result);
 printf("</pre>");
        
	    return $query;
	}

    /**
     *
     *
     * @param boolean $all, true: se muestra todo los teg
     *                     false: se muestra SOLO las que esten publicas
     * @return Doctrine\ORM\Query $dql   DQL Query Object
     */
    public function findAllQuery($all = true)
    {
        // Create our query
        $query = $this->createQueryBuilder('t');
        
        if ($all){
            $query->orderBy('t.publicacion', 'DESC')->getQuery();
        }
        else{ 
            
            $query->where($query->expr()->eq('t.published', "'true'"))->orderBy('t.publicacion', 'DESC')->getQuery();

        }

        return $query;
    }
}
