<?php

namespace Biblioteca\TegBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tuthorRepository extends EntityRepository
{
}
