biblioteca_teg:
    resource: "@BibliotecaTegBundle/Controller/"
    type:     annotation
    prefix:   /

biblioteca_user:
    resource: "@BibliotecaUserBundle/Controller/"
    type:     annotation
    prefix:   /

acme:
    resource: "@AcmeBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_change:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"    