# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    biblioteca.form.registration:
        class: Biblioteca\UserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: biblioteca_user_registration }
#    biblioteca_user.registration.form.type:
#        class:     Biblioteca\UserBundle\Form\Type\RegistrationFormType
#        arguments:     ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer"]
#        tags:
#            - { name:     form.type, alias:     biblioteca_user_registration }
#        scope:     request
#        public:     false